"""Add profile fields

Revision ID: c15b32766569
Revises: 
Create Date: 2025-10-18 00:35:51.396168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15b32766569'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apscheduler_jobs_next_run_time'))

    op.drop_table('apscheduler_jobs')
    
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cgpa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('graduation_year', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendly_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('biography', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('designation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_user_attendly_id', ['attendly_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_attendly_id', type_='unique')
        batch_op.drop_column('experience')
        batch_op.drop_column('department')
        batch_op.drop_column('designation')
        batch_op.drop_column('branch')
        batch_op.drop_column('biography')
        batch_op.drop_column('location')
        batch_op.drop_column('avatar')
        batch_op.drop_column('phone')
        batch_op.drop_column('attendly_id')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('graduation_year')
        batch_op.drop_column('cgpa')
        batch_op.drop_column('semester')
        batch_op.drop_column('batch')

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apscheduler_jobs_next_run_time'), ['next_run_time'], unique=False)

    # ### end Alembic commands ###